### ISSUE TITLE
Search bugs in SolidCP

### ISSUE THREAD

**Issue by FuseCP-BKruszewski** [FuseCP/SolidCP#100]
There are several bugs in the search mechanism in SolidCP:

- if you are searching in the main search field for an hosted exchange mailbox, you will get two results. One of them will throw an SolidCP error.
- The search field in "Drive maps" is case sensitive only. If you have a lot of drive mappings, you need to know the exact name to find it. But in this case a search field is useless.
- The search field in "RDS collections" doesn't find anything, even if you search for the exact name of the RDS collection.
- The search field in "RDS servers" will find all RDS servers, even if you are searching for a string, which doesn't existing in this list.

**Comment by berkut1** [comment]
It would also be great if a global search for virtual machines by IP is also added (fixed?) (currently only works with hostname or itemName)

GlobalSearch works through this class https://github.com/FuseCP/SolidCP/blob/master/SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/Code/Helpers/AjaxHandler.cs
