### ISSUE TITLE
MFA activation on Peer accounts not working

### ISSUE THREAD

**Issue by posixx** [FuseCP/SolidCP#133]
Activation of the MFA option on peer accounts is failing. The generation of the PinSecret and activating the MFA is not working when selecting the checkbox on the Peer account page. It simply does not update the user table.

When generating the PinSecret myself and set MfaMode to 1 in the usertable it works as expected; user receives email and can activate QR on device.

**Comment by FuseCP-TRobinson** [comment]
I have tried this on a peer account and it worked fine. Are you activating it as the peer or the main account?

**Comment by posixx** [comment]
I am enabling MFA on a peer account when logged in with serveradmin. After saving and opening the account details page again the MFA selectionbox is empty.

**Comment by FuseCP-TRobinson** [comment]
This was fixed in  #149 and will be included in V1.5.0
