### ISSUE TITLE
MFA issue on Hyperv vm creation.

### ISSUE THREAD

**Issue by kdovale** [FuseCP/SolidCP#140]
Not sure why this is happening, we upgraded to 1.4.9 and when we create a user account with a vm it gives an error as below when whmcs runs the create user and vm, the account seems to be created fine its the vm that fails to create.

CreateAccount Fault: (Code: 0, Message: UpdateUser Fault: (Code: 0, Message: SOAP Fault: (Code: 0, Message: SOAP-ERROR: Encoding: object has no 'MfaMode' property), Service ID: 3230)

**Comment by berkut1** [comment]
Hello,

That error means, that you didn't update the WHMCS Module.

**Comment by kdovale** [comment]
where can we get the latest version from, because  I downloaded it from solidcp and its still got the 2021 date on it..

**Comment by kdovale** [comment]
I pulled the correct version from the master and it works, but I would think the production zip would have the latest version updated . ;-)

**Comment by trevorrobinson** [comment]
Hello,

Sorry i was not aware of the WHMCS changes required for the latest version.

I have now release v1.1.4 and updated the ZIP located at https://installer.solidcp.com/Files/plugins/SolidCP.WHMCSModule.zip.

The changes have been pushed to the WHMCS Marketplace but awaiting approval.

Regards,

Trevor

**Comment by kdovale** [comment]
great the update is the fix 100% thx trevor
