### ISSUE TITLE
Twillio not working - This API is being discontinued

### ISSUE THREAD

**Issue by ergonet** [FuseCP/SolidCP#148]
It looks like SolidCP is using discontinued Twillio API - SMS password reset is not working. Error Below.

record severity="0" date="04/25/2023 10:14:00" ident="0"><text>This API is being discontinued. Please see [https://support.twilio.com/hc/en-us/articles/223181028-Switching-from-SMS-Messages-resource-URI-to-Messages-resource-URI-< ](https://support.twilio.com/hc/en-us/articles/223181028-Switching-from-SMS-Messages-resource-URI-to-Messages-resource-URI-%3C);/text><stackTrace>   at SolidCP.EnterpriseServer.OrganizationController.SendResetUserPasswordPincodeSms(Guid token, String phoneTo)</stackTrace></record></records></log>

**Comment by RickyKleinhempel** [comment]
Could be solved with #151
