### ISSUE TITLE
SimpleDNS 8.x provider not adding website DNS records

### ISSUE THREAD

**Issue by posixx** [FuseCP/SolidCP#15]
When adding a website using the SimpleDNS 8.x provider the A-records for the domain are not added to the DNS zone. Using older provider (SimpleDNS 5.x) works without issues.

![image](https://user-images.githubusercontent.com/2280400/69955061-159b4480-14fd-11ea-8b1b-f5b093f5f3db.png)

Using standard DNS configuration on service settings

**Comment by FuseCP-TRobinson** [comment]
This appears to be a issue when [host_name] is used and that match's the blank A record. If the record for [host_name] is removed the records are added fine.

API Call when [host_name] is used:

`From IP: 127.0.0.1
Method: PATCH
URL: /v2/zones/ttest2-simpledns-1.com/records
HTTP version: 1.1
--- Headers ---
Content-Length: 329
Content-Type: application/json; charset=utf-8
Authorization: Basic YWRtaW46UEBzczEwMDE=
Expect: 100-continue
Host: 127.0.0.1:8053
--- Payload ---
[{"Name":".ttest2-simpledns-1.com","Type":"A","TTL":1800,"Data":"185.189.180.99"},
{"Name":"*.ttest2-simpledns-1.com","Type":"A","TTL":1800,"Data":"185.189.180.99"},
{"Name":"www.ttest2-simpledns-1.com","Type":"A","TTL":1800,"Data":"185.189.180.99"},
{"Name":".ttest2-simpledns-1.com","Type":"A","TTL":1800,"Data":"185.189.180.99"}]
`

**Comment by posixx** [comment]
Yes you are correct, when removing [host_name] it works, but only for toplevel domains. As soon as i try to add a website for a subdomain that fails without [host_name]..
