### ISSUE TITLE
SolidCP 1.4.9 installer doesn't support MS SQL 2022

### ISSUE THREAD

**Issue by coax** [FuseCP/SolidCP#152]
Hello, when installing (not upgrading) **SolidCP Standalone Server** Setup (version **1.4.9**) on new Windows Server with **MS SQL Express 2022**, the setup gives error "This program can be installed on SQL Server 2005/2008/2012/2014/2016/2017/2019 only" and doesn't proceed with installing.

Any suggestions on how to bypass the error?

**Comment by FuseCP-TRobinson** [comment]
This has been fixed in commit 5faa505
