### ISSUE TITLE
1.4.9 Installer Standalone Server - Unable to create Database

### ISSUE THREAD

**Issue by Sharky521** [FuseCP/SolidCP#166]
**Describe the bug**
No matter what Windows Server OS or SQL Express version, the same error can be encountered. The Database is unable to be created via the Installer.
I've tried Windows OS versions 2016, 2019, and 2022 as well as SQL Express 2012, 2014, 2016, 2019, and 2022. All have given the same issue.

**To Reproduce**
1. Go to 1.4.9 installer
2. Click on Standalone Server
3. Proceed through install and wait.

**Expected behavior**
It's expected to complete the installation accordingly.

**Screenshots**

**SolidCP Info**
 - SolidCP Version:  1.4.9

**Desktop (please complete the following information):**
 - OS: Windows server - ANY Version
 - Browser NA
 - Version NA

**Additional context**
[12/17/2023 10:36:57 PM] ERROR: Create database error
System.Data.SqlClient.SqlException (0x80131904): Cannot create file 'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SolidCP.mdf' because it already exists. Change the file path or the file name, and retry the operation.

**Comment by FuseCP-TRobinson** [comment]
Hello,

The installer for 1.4.9 does work with SQL 2019. Following your error it looks like an SolidCP database already exists on the server.

If there is no database on the server please make sure to remove the .mdf and .log files from the MSSQL Data path.

Regards,

Trevor
