### ISSUE TITLE
dns issue displaying _domainkey records and similar

### ISSUE THREAD

**Issue by kdovale** [FuseCP/SolidCP#172]
is it possible to display the _domainkey dns records in the dns zones ? We are using msdns but the domainkeys get added but the clients cant see they are there to delete or edit them.

They are added in the msdnszone a _domainkeys in a folder, and listed like this but solidcp doesnt show them at all..
![solidcpdomainmeyissue](https://github.com/FuseCP/SolidCP/assets/7291726/cbb786f6-c59b-47c0-be68-7703673f20ed)

**Comment by FuseCP-TRobinson** [comment]
Hello,

Unable to replicate this issue with MSDNS2016 Provider. Do not there is currently a issue where the data can only be 255 charaters due to a issue in the Microsoft Powershell commands.

Regards,

Trevor

**Comment by kdovale** [comment]
Hi,

The solidcp doesnt display these subdomain records, ie _domainkey or any subfolders in the domain in msdns. However if we use powershell to return these records it does, but it seems its chopped off at 255. however, the full amount of data is not my concern, we need to be able to display these records even with only the first segment, and give the client the view that they can see it was added, and if required the option to delete the record. currently you add the record and it doesnt display so they assume it didnt add by default. So even if its a chopped version its better than not displaying at all.

using this script it returns all the info as requested

# Define DNS server and zone
$dnsServer = "server1"
$zoneName = "abc.co.za"

# Function to query only TXT records for a given zone
function Get-TxtRecords {
    param (
        [string]$dnsServer,
        [string]$zoneName
    )

    # Get all TXT records for the specified zone
    try {
        $txtRecords = Get-DnsServerResourceRecord -ComputerName $dnsServer -ZoneName $zoneName -RRType "TXT" -ErrorAction Stop
        Write-Output "TXT Records for zone '$zoneName' on server '$dnsServer':"

        $txtRecords | ForEach-Object {
            try {
                # Extract TXT record data
                $recordInfo = @{
                    Name       = $_.HostName
                    RecordType = $_.RecordType
                    TTL        = $_.TimeToLive
                    RecordData = $_.RecordData.DescriptiveText
                }

                # Output the TXT record information
                [PSCustomObject]$recordInfo
            }
            catch {
                Write-Output "Failed to process TXT record $($_.HostName): $_"
            }
        }
    }
    catch {
        Write-Output "Failed to query TXT records: $_"
    }
}

# Run the function and output results
Get-TxtRecords -dnsServer $dnsServer -zoneName $zoneName


this then returns all the txt records for the domains ie

TTL        RecordType Name                                        RecordData                                                                                         
---        ---------- ----                                        ----------                                                                                         
1.00:00:00 TXT        @                                           google-site-verification=12345S-xxxxxx3aJn_xxxxxxf0xEgZIU                               
1.00:00:00 TXT        @                                           v=spf1 mx ip4:197.237.24.186/26 -all                                                               
1.00:00:00 TXT        @                                           MS=2312390BA58A0D294512312363DA913F233150                                                        
1.00:00:00 TXT        _dmarc                                      v=DMARC1; p=none; rua=mailto:dmarc@abc.co.za; ruf=mailto:dmarc@abc.co.za; adkim=r; asp...
1.00:00:00 TXT        abc.co.za._report._dmarc               v=DMARC1                                                                                           
1.00:00:00 TXT        xxx.co.za._report._dmarc                   v=DMARC1                                                                                           
1.00:00:00 TXT        _domainkey                                  o=~; r=dmarc@abc.co.za                                                                        
00:05:00   TXT        8DCCdfsdfsdf._domainkey                  p=MIIBIjANBgkqhkiG9w0dfsdfsdfAOCAQ8AMIIBCgKCAQEApPdfssfsdfsdOBEUCvrhghtdfsdfOtVteDiyb+Lgte/6C7...
00:05:00   TXT        mail._domainkey                             p=MIIBIjANBgkqhkiG9w0BAQEFAsdfsdfsdfgKCAQEAv8O+EGsdfdsfsycHh8AHWkSWmgaziDadfsdfdsfPycTbwIK...
00:15:00   TXT        pmta._domainkey                             p=MIIBIjANBgkqhkiG9w0BdfsdfsdfsdfsdfsdfgKCAQEAlP7K4QmyTvMS0BvsdfsdfsdffIi+dJTlhkt3CdB9KJbTs...
1.00:00:00 TXT        _fmbla                                      159b35-8ea0-abcd-cder-9f6ba3fb76                                                               
1.00:00:00 TXT        _spf                                        v=spf1 ip4:197.237.24.186/26 -all                                                                  
1.00:00:00 TXT        hq2osctxukiubhxd_xhhtor-y6rvgdfgdfgdgdfgd _acme-challenge.abc.co.za

**Comment by kdovale** [comment]
hi trevor let me show you what I see on any domain, in msdns and the solidcp, you will see in solidcp the domainkey and sub domain records dont show like yours, as you can see the domain jey record is there in msdns , but in solidcp there is zero, i also added a cp sub, and it too isnt showing..

![dnsissue](https://github.com/user-attachments/assets/b89c7cc7-2fb3-48b9-a9fd-ea037257c360)

**Comment by FuseCP-TRobinson** [comment]
Hey,

If you do an Get-DnsServerResourceRecord with the zone name does it show these records?

Regards,

Trevor

**Comment by kdovale** [comment]
PS C:\Users\Administrator> Get-DnsServerResourceRecord hoedjiesbaaihotel.co.za
 
HostName                  RecordType Type       Timestamp            TimeToLive      RecordData                                        
--------                  ---------- ----       ---------            ----------      ----------                                        
@                         A          1          0                    1.00:00:00      196.22.224.xxx                                    
@                         NS         2          0                    1.00:00:00      ns04.xxx.co.za.                              
@                         NS         2          0                    1.00:00:00      ns03.xxx.co.za.                              
@                         SOA        6          0                    1.00:00:00      [2022060960][ns03.xxx.co.za.][dnsadmin.xxx...
@                         MX         15         0                    1.00:00:00      [20][smtp2.hoedjiesbaaihotel.co.za.]              
@                         MX         15         0                    1.00:00:00      [10][mail.hoedjiesbaaihotel.co.za.]               
@                         TXT        16         0                    1.00:00:00      v=spf1 mx include:_spf.xxxx.co.za -all        
*                         A          1          0                    1.00:00:00      196.22.224.xxx                                    
_dmarc                    TXT        16         0                    1.00:00:00      v=DMARC1; p=none; ***@***.***
_domainkey                TXT        16         0                    1.00:00:00      o=~; ***@***.***                       
mail._domainkey           TXT        16         0                    00:05:00        p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0...
autodiscover              A          1          0                    1.00:00:00      196.22.224.xxx                                    
awstats                   A          1          0                    1.00:00:00      196.22.224.xxx                                    
cp                        A          1          0                    1.00:00:00      196.22.224.xxx                                    
ftp                       A          1          0                    1.00:00:00      196.22.224.xxx                                    
imap                      CNAME      5          0                    1.00:00:00      mail.hoedjiesbaaihotel.co.za.                     
mail                      A          1          0                    00:30:00        196.22.224.xxx                                    
mssql                     A          1          0                    1.00:00:00      196.22.224.xxx                                    
mysql                     A          1          0                    1.00:00:00      196.22.224.xxx                                    
mysql8                    A          1          0                    1.00:00:00      196.22.224.xxx                                    
pop                       CNAME      5          0                    1.00:00:00      mail.hoedjiesbaaihotel.co.za.                     
pop3                      CNAME      5          0                    1.00:00:00      mail.hoedjiesbaaihotel.co.za.                     
smtp                      CNAME      5          0                    1.00:00:00      mail.hoedjiesbaaihotel.co.za.                     
smtp2                     A          1          0                    1.00:00:00      196.22.224.xxx                                    
stats                     A          1          0                    1.00:00:00      196.22.224.xxx                                    
webmail                   CNAME      5          0                    1.00:00:00      mail.hoedjiesbaaihotel.co.za.                     
www                       A          1          0                    1.00:00:00      196.22.224.xxx                                    
 
 
Here you can see the returned pointers
 
Kind Regards
 
Keith Dovale
