### ISSUE TITLE
SimpleDNS 9.x Provider not working

### ISSUE THREAD

**Issue by enguard1** [FuseCP/SolidCP#207]
When using the SimpleDNS 9.x Provider with SimpleDNS Version 9.1 (Build 116) it does not work with the following error:

[12/5/2024 4:28:28 PM] WARNING: SimpleDNS 8 API Call (PATCH) Failed - Failed to parse patch item 1: Does not belong in zone

We have been using the SimpleDNS 8.x Provider since SolidCP 1.4.9 and now in 1.5.0

**Comment by FuseCP-TRobinson** [comment]
This should be fixed in f8a24da51fbc31966f2b5be9946c79ebdf435a58

We will push up a new build in the next 48H with these fixes in.

**Comment by enguard1** [comment]
Are you releasing 1.5.1? or simply overwriting existing files in the 1.5.0 release?
