### ISSUE TITLE
[HyperV] Additional VHDX bug

### ISSUE THREAD

**Issue by IvanSchulz** [FuseCP/SolidCP#212]
**Describe the bug**
If you have an additional VHDX not in "Virtual Hard Disks" folder and then add another one, this causes an error, that both VHDX have the same name and cannot be mapped correctly in SolidCP.

**To Reproduce**
1. Add an additional VHDX
2. Move it from "Virtual Hard Disks" folder
3. Edit the VHDX path in the HyperV and in the SolidCP database
4. Add an another additional VHDX
5. Now it is no longer possible to change VM configuration in SolidCP (HDD size error)

**Expected behavior**
Additional VHDX should be mapped correctly, even if they are not in the same folder

**SolidCP Info**
 - SolidCP Version:  [1.5.0]

**Comment by berkut1** [comment]
@IvanSchulz 
Hello, 

How did it happen that the VHDX disk ended up outside the Virtual Hard Disks folder? Or was it manually added bypassing the panel?

**Comment by IvanSchulz** [comment]
Hi @berkut1 ,

yes, we sometimes moved it manually due to problems with the backup software. Now there should be no issues, no matter where VHDX is located.
