### ISSUE TITLE
[HyperV2012R2+] maxCores is calculated locally when remote HyperV is selected

### ISSUE THREAD

**Issue by FuseCP-TRobinson** [FuseCP/SolidCP#219]
**Describe the bug**
When using HyperV on a remote Hyper-V server it will calculate the cores on the SolidCP Server machine not the HyperV Host.

**To Reproduce**
1. Create a VM with 4 cores and install SolidCP Server on there
2. Install the HyperV provider in remote mode
3. Create a hosting plan with more cores than the SolidCP Server machine.
4. Create a VM and see its limited to the cores of the SolidCP Server

**Expected behavior**
SolidCP to fetch the cores from the HyperV server not local machine in GetProcessorCoresNumber

**SolidCP Info**
 - SolidCP Version:  1.5.1

This was also discussed in #218 but moving here as its a valid report of a issue

**Comment by berkut1** [comment]
@FuseCP-TRobinson Can you check this fix?
Replace this:
https://github.com/FuseCP/SolidCP/blob/3de665b7bbb7ccd75214ec38d082f1ec6efc9a80/SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/HyperV2012R2.cs#L2146-L2154

To:
```c#
public int GetProcessorCoresNumber()
{
    int coreCount = 0;
    Wmi cimv2 = new Wmi(ServerNameSettings, Constants.WMI_CIMV2_NAMESPACE);

    foreach (var item in cimv2.ExecuteWmiQuery("Select * from Win32_Processor"))
    {
        coreCount += int.Parse(item["NumberOfLogicalProcessors"].ToString());
    }
    return coreCount;
}
```

**Comment by FuseCP-TRobinson** [comment]
@berkut1 That works and now it shows me 40 in the dropdown. Can you commit it to the code or want me to?

**Comment by berkut1** [comment]
@FuseCP-TRobinson 
I'm glad it works! Feel free to go ahead and commit the changes :)
