### ISSUE TITLE
[SimpleDNS] Creating TXT record

### ISSUE THREAD

**Issue by FuseCP-TRobinson** [FuseCP/SolidCP#52]
**Describe the bug**
When creating a TXT record such as "v=spf1 redirect=Somewhere.net" in SolidCP it is applied to SimpleDNS as multiple strings ("v=spf1" "redirect=Somewhere.net")

**To Reproduce**
1. Go to Users domain
2. Edit DNS
3. Add record with data: v=spf1 redirect=Somewhere.net

**Expected behavior**
To be created as one string.

**SolidCP Info**
 - SolidCP Version:  1.4.7

**Additional context**

Workaround: Create record with "" around the data.

**Comment by enguard1** [comment]
This particularly affects SPF records which generally look like this:

v=DKIM1; k=rsa; h=sha256; p=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANLjXlznBtWqS+LOY6+1E/RP0/Oc0tUSADIAo5xVR5r5Jz1gxJnC5c5ydGKriyM9SPmOOuhL8XQk0LZvHqMbXa0CAwEAAQ==

The workaround is to put the entire thing between quotes:

"v=DKIM1; k=rsa; h=sha256; p=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANLjXlznBtWqS+LOY6+1E/RP0/Oc0tUSADIAo5xVR5r5Jz1gxJnC5c5ydGKriyM9SPmOOuhL8XQk0LZvHqMbXa0CAwEAAQ=="
