### ISSUE TITLE
not all RDP Collection settings are being saved.

### ISSUE THREAD

**Issue by robsiera** [FuseCP/SolidCP#54]
The Stored Procudures "GetRDSCollectionById" "UpdateRDSCollectionSettings" are missing three fields that thus never get updated by the UI (RDP Collection > Settings).

* SecurityLayer
* EncryptionLevel
* AuthenticateUsingNLA

Can someone please add those? 
The C# code to handle them is all there. So I guess that someone forgot to update the update_db.sql file when deploying these fields?

**Comment by FuseCP-TRobinson** [comment]
Fixed as per commit. Will be included in the next version of SolidCP.
