### ISSUE TITLE
[DNS] - Feedback requested about a validator of new records

### ISSUE THREAD

**Issue by FuseCP-BKruszewski** [FuseCP/SolidCP#65]
If you want to create new or edit existing DNS records for e.g. domain.com, it's currently possible to enter also "test.domain.com" into the record field.

On SimpleDNS I suppose that the API is "fixing" it, so the right record "test.domain.com" will be created, doesn't matter if you enter only "test" or "test.domain.com".

On MS DNS the correct record will only be created, if you enter "test" only. If you enter "test.domaind.com", then a "test.domain.com.domain.com" record will be created.

In general, does it make sense to "cut" the FQDN at the end of the record form field in the background, so the experience will be consistent over all DNS providers? Or maybe it make more sense to create a kind of validator to show an error, if "test.domain.com" is entered into the record field? In this case it would be good to add a text after the form field, showing ".domain.com", so the user will notice to type the record without the FQDN.

How do other DNS software handle it in SolidCP?

**Comment by FuseCP-TRobinson** [comment]
With the recent changes to DNS we now show the .domain.com next to the record to make it more clear.

Im not sure if it makes sense to ignore the input and expect the person made a error. I believe the SimpleDNS might do this on their API.
