### ISSUE TITLE
[Exchange] Automatic replies for mailboxes (out of office)

### ISSUE THREAD

**Issue by FuseCP-BKruszewski** [FuseCP/SolidCP#7]
Currently there is no possibility to manage automatic replies for mailboxes via SolidCP.

It would be nice to get a new tab inside a mailbox in SolidCP with automatic replies settings. In my opinion this tab or pane inside the settings tab should be only visible if it's a regular mailbox, if automatic replies are enabled in the hosting space quota and maybe in the mailbox plan (see my questions below).

The following values should be editable and pushed via this PS command:
```
Set-MailboxAutoReplyConfiguration
-Identity
-AutoReplyState
-StartTime  (if AutoReplyState = scheduled)
-EndTime (if AutoReplyState = scheduled)
-ExternalAudience
-ExternalMessage (if ExternalAudience = None, then ExternalMessage = $null and the field is disabled.)
-InternalMessage
```
InternalMessage and ExternalMessage should be editable with the already implemented TinyMCE editor in SolidCP to create a clear HTML output. In this case all quotes inside the HTML should be escaped ( \" ) while passed to the powershell command, otherwise it will throw errors (see my questions below).

Please be aware, that Exchange handles e-mails  between two different tenants/organizations within the same environment as internal messages without any 3rd party extensions. 

**Additional questions to all, who see it as a useful feature:**

- Where is the best place to put these automatic replies settings inside the mailbox configuration? In a seperate tab or as a panel inside the settings tab?

- Does it make sense or is it even possible to allow oof settings also for shared and/or ressource mailboxes?

- Does it make sense to create also a quota for oof inside the mailbox plans? Maybe someone want to make some mailbox plans, which are not allowed to have oof settings while on a global hosting space level it's allowed for all other mailboxes. On the other side it's still allowed for everyone via OWA, so don't know if it would be a useful quota or not.

- Is it enough to escape quotes ( \" ) from Internal and ExternalMessage HTML output to avoid errors, or should be other checks/regex/sanitization rules implemented?

**Comment by FuseCP-BKruszewski** [comment]
This is an example how O365 admin center handles it: https://www.youtube.com/watch?v=bcZS1VyPD5Y

**Comment by FuseCP-MTiggelaar** [comment]
**- For where to put it:**
I would say the settings tab? (still has plenty of space etc).
**- Are shared / resource mailboxes supported?:**
Shared mailboxes are supported, resource i am not sure (guess we have to test that).
**- Does it make sense for mailbox quota?:**
I'm not sure, it's mainly an admin function in either case (as it's via the panel). but it might be useful to not allow anyone to set for example a top level executive's OOF as a sys admin ;-)
**- is it enough to escape " ?:**
Following exchange doc's exchange will add html and body tags aswell, so i would make sure those are excluded from being entered (lets say when someone copies over a html template etc).
