### ISSUE TITLE
[MsSQL] Copy to Folder Path1

### ISSUE THREAD

**Issue by FuseCP-TRobinson** [FuseCP/SolidCP#76]
**Describe the bug**
When trying to backup a database to a folder (Either one time or scheduled) it will error with 

![fO6Dsh2d3X](https://user-images.githubusercontent.com/35742838/116111493-9b99cb80-a6ae-11eb-99c9-38f4f0feb5af.png)

**To Reproduce**
1. Go to MsSQL Database
2. Select backup database
3. Select to Copy to Folder

**Expected behavior**
SQL backup to complete to the folder

**Screenshots**
- See above

**SolidCP Info**
 - SolidCP Version:  1.4.7

**Additional context**
https://solidcp.com/forum/question/error-executing-backup-task-value-cannot-be-null-parameter-name-path1/

**Comment by FuseCP-TRobinson** [comment]
This issue appears to be related to a invalid hosting space file system. If OS not present or there is other issues such as filemanager not working.

**Comment by markdonne** [comment]
We are having this problem and we do have an OS present and we can upload with file manager, the only problem for is the SQL backups do not work
