### ISSUE TITLE
portal RTL support for Arabic 

### ISSUE THREAD

**Issue by eg2-hack** [FuseCP/SolidCP#77]
i translate portal to Arabic language but for final need portal to support RTL also There are phrases that have not been accessed and translated

[SolidCP Language Pack ar-AE 1.4.7.zip](https://github.com/FuseCP/SolidCP/files/6408317/SolidCP.Language.Pack.ar-AE.1.4.7.zip)

[Resources.zip](https://github.com/FuseCP/SolidCP/files/6408358/Resources.zip)

**Comment by FuseCP-TRobinson** [comment]
Added support in 2bfde8cbd46c1e6623be65430d22eb349aa02715 for RTL.

@FuseCP-MTiggelaar Can you add the language files to the project? It will auto use RTL when using ar-AE as it does a lookup on the language Culture.

**Comment by anajgroup** [comment]
what about persian language? is it possible to show the portal rtl when language is fa-ir?

**Comment by FuseCP-TRobinson** [comment]
SolidCP will support RTL on all languages which are marked as RTL following Microsoft's CultureInfo
