### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by AaronSadlerUK** [FuseCP/SolidCP#83]
Can the API endpoints be documented.

And can the API authentication method be documented, that way I can build an SDK.

I can't read PHP so the WHMCS module is useless for me

**Comment by FuseCP-TRobinson** [comment]
Hello,

At the current moment we are not planning to document the API endpoints until we have moved from SOAP to Restless.

Once we have moved to the new API we will fully document it. IF your looking for specific help regarding API i would suggest posting on the forum where we can provide better assistance.

Regards,

Trevor
